apiVersion: v1
kind: Service
metadata:
  name: egov-simple-react
  labels:
    app.kubernetes.io/name: egov-simple-react
    app.kubernetes.io/part-of: egovframe-template
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: egov-simple-react
  ports:
    - name: http
      port: 8080
      targetPort: http
